---
kind: pipeline
type: docker
name: Docker

trigger:
  branch:
    - master
  event:
    - pull_request

steps:
  - name: build-docker-image
    image: plugins/docker
    settings:
      repo: cedrichopf/drone-status
      dry_run: true
