---
kind: pipeline
type: docker
name: Test Plugin

trigger:
  branch:
    - master
  event:
    - pull_request

steps:
  - name: create-status
    image: python:3.8-slim-buster
    commands:
      - "python -m pip install -r requirements.txt"
      - "python main.py"
    environment:
      PLUGIN_API_TOKEN:
        from_secret: GITHUB_API_TOKEN
      PLUGIN_STATE: success
      PLUGIN_CONTEXT: drone-status/test-plugin
      PLUGIN_DESCRIPTION: Status created successfully

---
kind: pipeline
type: docker
name: Docker

trigger:
  branch:
    - master
  event:
    - pull_request

steps:
  - name: build-docker-image
    image: plugins/docker
    settings:
      repo: cedrichopf/drone-status
      dry_run: true

---
kind: pipeline
type: docker
name: Release

trigger:
  event:
    - tag

steps:
  - name: create-tarball
    image: ubuntu:latest
    commands:
      - "tar -czvf drone-status-v${DRONE_SEMVER}.tar.gz main.py config drone github Pipfile Pipfile.lock requirements.txt README.md LICENSE"
  - name: publish-github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_API_TOKEN
      title: v${DRONE_SEMVER}
      files:
        - drone-status-*.tar.gz
      checksum:
        - sha256
        - sha512
  - name: push-to-docker-hub
    image: plugins/docker
    settings:
      auto_tag: true
      repo: cedrichopf/drone-status
      username:
        from_secret: DOCKER_HUB_USERNAME
      password:
        from_secret: DOCKER_HUB_PASSWORD
  - name: push-to-github-packages
    image: plugins/docker
    settings:
      auto_tag: true
      repo: cedrichopf/drone-status
      registry: docker.pkg.github.com
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_API_TOKEN

---
kind: pipeline
type: docker
name: Latest-Release

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: push-to-docker-hub
    image: plugins/docker
    settings:
      tags: latest
      repo: cedrichopf/drone-status
      username:
        from_secret: DOCKER_HUB_USERNAME
      password:
        from_secret: DOCKER_HUB_PASSWORD
  - name: push-to-github-packages
    image: plugins/docker
    settings:
      auto_tag: true
      repo: cedrichopf/drone-status
      registry: docker.pkg.github.com
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_API_TOKEN
